### PR TITLE
Add ibc usdc and ibc atom as gas prices for neutron-1

### PR DESCRIPTION
**Pull request by NeverHappened**

### CODE REVIEW

**Comment by JeremyParish69** [comment]
Can you please add these tokens to Neutron's assetlist? It's so viewers aren't guessing which tokens these are referring to, especially if the original ibc channel changes, it could be hard to find out what it is.

**Comment by JeremyParish69** [comment]
Thanks, there actually a lot that could be fixed here, thought. Are you able to grant modify permissions to repo maintainers so I can fix it up?

**Comment by NeverHappened** [comment]
Oh, I think so, but we can only do it tomorrow. Or maybe you can use review suggestions to show correct code?

**Comment by JeremyParish69** [comment]
This should do it:
https://github.com/neutron-org/chain-registry/pull/4

**Comment by NeverHappened** [comment]
Oh, nice! Thanks a lot for helping!

**Pull request merged**
