### PR TITLE
docs(agoric): add Agoric chain and assetlist

### PR DESCRIPTION
**Pull request by michaelfig**
Parameters for the current Agoric mainnet.

### CODE REVIEW

**Comment by sunnya97** [comment]
@michaelfig are BLD and RUN native sdk.Coins?  Or are they tokens in a new Agoric VM token standard?

Cause if latter, we should add it to the assetlist schema:  https://github.com/cosmos/chain-registry/blob/master/assetlist.schema.json#L33

**Comment by michaelfig** [comment]
> @michaelfig are BLD and RUN native sdk.Coins? Or are they tokens in a new Agoric VM token standard?

They're native sdk.Coins.

**Comment by jackzampolin** [comment]
Exciting!

**Comment by sunnya97** [comment]
@michaelfig Is IBC enabled for the chain?

**Pull request merged**
