### PR TITLE
chore(api): Remove stale api endpoints

### LINKED ISSUE #915: is there a policy for apis are unresponsive?
the first two rpcs on evmos have been down for days. do we have a policy to remove them if they are broken?

  `"apis": {
    "rpc": [
      {
        "address": "https://rpc-evmos.ecostake.com",
        "provider": "ecostake"
      },
      {
        "address": "https://rpc-evmos.whispernode.com",
        "provider": " WhisperNode 🤐"
      }`

### PR DESCRIPTION
**Pull request by Reecepbcups**
Closes #915 

## Change Log:
```
- Makes a _scripts folder with stale endpoints clearing logic (down for >30 days)
```

## Removed Endpoints (Mar 29, 2022)
```
[-] jackal rpc https://rpc-jackal.huginn.tech
[-] rebus rpc https://rpc-rebus.nodeist.net
[-] rebus rpc https://rpc-rebus.huginn.tech
[-] rebus rest https://api-rebus.nodeist.net
[-] stargaze rpc https://stargaze.c29r3.xyz:443/rpc
[-] stargaze rest https://stargaze.c29r3.xyz:443/api
[-] osmosis rpc https://osmosis.rpc.interchain.ivaldilabs.xyz
[-] osmosis rest https://osmosis.rest.interchain.ivaldilabs.xyz
[-] bitcanna rpc https://rpc-bcna.kjinc.io
[-] bitcanna rest https://api-bcna.kjinc.io
[-] kujira rpc https://rpc-kujira.huginn.tech
[-] echelon rpc https://ech-rpc.softpaws.xyz
[-] echelon rest https://ech-api.softpaws.xyz
[-] sentinel rpc https://sentinel-rpc2.badgerbite.io
[-] arkh rpc https://asc-dataseed.arkhadian.com
[-] arkh rest https://asc-blockchain-api.arkhadian.com
[-] sifchain rpc https://sif-rpc.kleomedes.network
[-] sifchain rest https://sif-api.kleomedes.network
[-] cerberus rpc https://rpc-cerberus.ecostake.com
[-] cerberus rpc https://cerberus-rpc.polkachu.com
[-] cerberus rpc https://cerberus-rpc.kleomedes.network
[-] cerberus rest https://rest-cerberus.ecostake.com
[-] cerberus rest https://cerberus-api.polkachu.com
[-] cerberus rest https://cerberus-api.kleomedes.network
[-] evmos rpc https://evmos.rpc.interchain.ivaldilabs.xyz
[-] evmos rpc https://rpc-evmos.goldenratiostaking.net
[-] evmos rest https://evmos.rest.interchain.ivaldilabs.xyz
[-] stride rpc https://stride.rpc.interchain.ivaldilabs.xyz
[-] stride rest https://stride.rest.interchain.ivaldilabs.xyz
[-] secretnetwork rpc https://rpc.secret.forbole.com
[-] cosmoshub rpc https://cosmoshub.rpc.interchain.ivaldilabs.xyz
[-] cosmoshub rest https://cosmoshub.rest.interchain.ivaldilabs.xyz
[-] cosmoshub rest https://rest-cosmoshub.architectnodes.com
[-] nomic rpc https://rpc.nomic.interbloc.org
[-] axelar rpc https://axelar.rpc.interchain.ivaldilabs.xyz
[-] axelar rest https://axelar.rest.interchain.ivaldilabs.xyz
[-] mars rpc https://rpc-mars.nodeist.net:443
[-] mars rest https://api-mars.nodeist.net:443
[-] juno rpc https://juno.rpc.interchain.ivaldilabs.xyz
[-] juno rpc https://rpc-juno.goldenratiostaking.net
[-] juno rest https://juno.rest.interchain.ivaldilabs.xyz
```

### CODE REVIEW

**Comment by mikedotexe** [comment]
dammmmn. nice!

**Comment by staking-explorer** [comment]
We fully support API cleanup. In addition to unavailable APIs, incorrect chain identifiers, REST/RPC confusion, there is a separate type of problematic API that causes the greatest problems for service developers. These are public nodes that have run out of disk space. These nodes report that they are fully synchronized. Although they just hung up. And the validators don't care. Because most nodes are added by validators solely to increase their positions in the RESTAKE. And we suffer. Due to such public nodes, we cannot launch our project in full. We are now analyzing all these nodes and are going to roll out some kind of automated solution for removing such nodes. Massive Registry Cleanup Coming! So validators, please keep an eye on the free space on your servers.

**Comment by dylanschultzie** [comment]
@staking-explorer space isn't the issue there, actually. When a node hangs like that, it's due to it being overwhelmed by queries. It would be more appropriate to say "developers please stop abusing public nodes"

**Comment by dylanschultzie** [comment]
@JeremyParish69 this seems cool to me, what do you think? I'd want to purge the current changes and keep the script, but the point stands - this script seems worthy of merging.

**Comment by JeremyParish69** [comment]
I was hesitant before because people used to try to remove nodes that appeared down, but it turned out they just didn't know how to query it. Also have seen some teams ask to be notified once their node is down for a couple days rather than removing it. I suppose 30 days down is fair for removal, but I hope we can be confident in the script to correctly identify whether nodes are truly down and not just think it's down because this (but not others) is being blocked. Generally I'm ok with it and some cleanup will do some good.

**Comment by dylanschultzie** [comment]
@JeremyParish69 

I reviewed the code, and it looks simple and reasonable. It uses `https://status.cosmos.directory/akash` to check the last successful time. It makes sense that teams would want to be notified before their info is removed, but also, 30 days down is quite a bit. That makes it a liability, not an asset.

**Comment by JeremyParish69** [comment]
Interesting idea. Can be brought up again, but this PR has a lot of conflicts and seems abandoned

**Comment by Reecepbcups** [comment]
@JeremyParish69 I will bring up a new PR in the morning :)

**Pull request closed without merging**
