### PR TITLE
Add Hunters endpoints for BlockHunters

### PR DESCRIPTION
**Pull request by blockhunters-dev**

### CODE REVIEW

**Comment by reversesigh** [comment]
Please use a proper PR title such as "Add Hunters endpoints for BlockHunters"

**Comment by blockhunters-dev** [comment]
Maybe you could mention this rule in the README.md and stop applying it arbitrarily if it's so important to use proper PR titles, right?

There are merged PRs that use exactly "Update chains.json"

**Comment by blockhunters-dev** [comment]
@reversesigh

**Comment by reversesigh** [comment]
@blockhunters-dev  This was updated to the README last week (https://github.com/cosmos/chain-registry/blob/master/README.md) - apologies for any frustration. Not trying to be difficult.

**Comment by dylanschultzie** [comment]
@blockhunters-dev there's no need to be rude. 

@reversesigh could have simply closed your PR due to not following instructions, but did not.

**Comment by JeremyParish69** [comment]
This PR otherwise looks fine but cannot merge due to conflicts. Closing due to age/staleness, but can be reopened.

**Pull request closed without merging**
