### PR TITLE
Update _IBC nois-sei.json

### PR DESCRIPTION
**Pull request by purpleguy99**
Data provided from 
ibc - transfer https://ibc.nois.network/connections/connection-11/channels/transfer:channel-43
ibc - wasm https://ibc.nois.network/connections/connection-11/channels/wasm.nois1acyc05v6fgcdgj88nmz2t40aex9nlnptqpwp5hf8hwg7rhce9uuqgqz5wp:channel-44

### CODE REVIEW

**Comment by JeremyParish69** [comment]
IBC channels cannot be changed without Governance Approval from both chains.

**Comment by purpleguy99** [comment]
Please check the current chains they not exists, i updating my ibc, cause i pushed wrong in previous

**Comment by JeremyParish69** [comment]
Well, I'm trusting that site, but it appears the previously registered (supposed) connection is invalid.

**Comment by purpleguy99** [comment]
Thank you!

**Pull request merged**
