### PR TITLE
add kichain testnet to registry

### PR DESCRIPTION
**Pull request by corentinfoure**

### CODE REVIEW

**Comment by sunnya97** [comment]
For testnets, please use a different `chainname`.  Chain names are meant to unique, even between mainnets and testnets.

**Comment by sunnya97** [comment]
Can you remove the dash please

We decided to keep chain names as only alphanumeric

**Comment by sunnya97** [comment]
(also update the folder name too)

**Comment by sunnya97** [comment]
Thanks!

**Comment by corentinfoure** [comment]
@sunnya97 sorry, for the format of the JSON, I fixed the issues the trailing comas 🤦

**Pull request merged**
