### PR TITLE
Add Apeiron Nodes rpc-seed endpoints on chain.json

### PR DESCRIPTION
**Pull request by Panvasi**
Added Apeiron Nodes seed and rpc.

### CODE REVIEW

**Comment by JeremyParish69** [comment]
Please use a more descriptive PR titles

**Comment by Panvasi** [comment]
> Please use a more descriptive PR titles

Done

**Comment by reversesigh** [comment]
> > Please use a more descriptive PR titles
> 
> Done

I don't see any changes. He means for you to change the name of the the PR itself (you can do this by clicking edit on the PR title at the top of this page).

**Comment by Panvasi** [comment]
> > > Please use a more descriptive PR titles
> > 
> > Done
> 
> I don't see any changes. He means for you to change the name of the the PR itself (you can do this by clicking edit on the PR title at the top of this page).

Now it's okay?🤔

**Pull request merged**
