### PR TITLE
chore: Mintscan not picking up /ixo/info details - now added

### PR DESCRIPTION
**Pull request by alwyn-ixo**

### CODE REVIEW

**Comment by JeremyParish69** [comment]
We already have this under the impacthub/ [folder](https://github.com/cosmos/chain-registry/tree/master/impacthub). The chain_name must match the folder name.

**Comment by alwyn-ixo** [comment]
@JeremyParish69 Hi - thx for the review.
The chain id changed from impacthub to ixo in March.
At the time we agreed that too many other parties may have dependencies to the impacthub folder.
However, our main interest is to have Mintscan pick up this configuration, which it is not.
https://www.mintscan.io/ixo

**Comment by JeremyParish69** [comment]
> @JeremyParish69 Hi - thx for the review. The chain id changed from impacthub to ixo in March. At the time we agreed that too many other parties may have dependencies to the impacthub folder. However, our main interest is to have Mintscan pick up this configuration, which it is not. https://www.mintscan.io/ixo

I see. We should let Mintscan know where to look since the chain name they use won't always align with the folder name.

**Comment by alwyn-ixo** [comment]
@JeremyParish69 
Notified Cosmostation and they updated on their side.
All is well - thx!

**Pull request closed without merging**
