### PR TITLE
Adds chains twitter @s

### PR DESCRIPTION
**Pull request by Reecepbcups**
also fixed some minor formatting :)

Should I tweak it to be the following, or is current fine?

```
# current
"twitter": "@blockchain"

# possible:
twitter: {
    "tag": "@blockchain"
    "id": "1337"
}
```

### CODE REVIEW

**Comment by JeremyParish69** [comment]
@Reecepbcups note, there has been some pushback on this. Although there are some obvious benefits to this, there is also possible drawbacks (scams?). One major concern is that the Twitter account is not an on-chain verifiable property of a chain (although, neither is website).

**Comment by vexxvakan** [comment]
> @Reecepbcups note, there has been some pushback on this. Although there are some obvious benefits to this, there is also possible drawbacks (scams?). One major concern is that the Twitter account is not an on-chain verifiable property of a chain (although, neither is website).

Theres verfication of twitter accounts on Keybase, maybe use the keybase identity as identifier?

**Comment by Reecepbcups** [comment]
> @Reecepbcups note, there has been some pushback on this. Although there are some obvious benefits to this, there is also possible drawbacks (scams?). One major concern is that the Twitter account is not an on-chain verifiable property of a chain (although, neither is website).

Personally I need it for my pyhthon-ibc bots [governance tagging](https://twitter.com/CosmosGovNotifs) which is useful so people can see the actual communications behind the proposals. I think its a more useful point of contact than a website IMO, so long as we can confirm new chains are actually said twitter account.

This just means more work for developers in the future who may want non on chain data for basic information of chains in the registry.

**Comment by dylanschultzie** [comment]
@Reecepbcups why not query their keybase identity and grab their twitter from there?

**Comment by Reecepbcups** [comment]
@dylanschultzie This is a REALLY good idea for my future vote notification bot

But this PR is for individual chains twitter @'s, not validators

I mean I guess I could create a x/information module or smart contract for an official link for chain's: website, twitter, contact, etc
Seems overkill though

**Comment by dylanschultzie** [comment]
@Reecepbcups oh wow, you're right, my apologies. I saw `governance tagging`, and my mind immediately went to validators.

**Comment by ValarDragon** [comment]
I don't like this. What does it mean to be a chain's twitter?

There is no "Ethereum" twitter for instance.

**Review by ankurdotb — APPROVED** [review]

**Comment by JeremyParish69** [comment]
Closing for now. Discussion can continue on chats or a dedicated Issue.

**Pull request closed without merging**
