### PR TITLE
feat: add additional native Kava assets - HARD and SWP

### PR DESCRIPTION
**Pull request by karzak**
Question: How should I handle `denom_units`?

For HARD and SWP, the native chain unit is `hard`, and `swp`, and they are each equivalent to 1^10-6 of 1 HARD, 1 SWP token.

### CODE REVIEW

**Comment by sunnya97** [comment]
@karzak the base unit here is supposed to be the "smallest unit".  Like `ukava`.  Is it also `uhard` and `uswap`?  If so, I can fill those in

**Comment by karzak** [comment]
Interanally, `hard` is the smallest unit, it's just worth 1*10**-6 of the exchange unit (HARD). So 1000000 hard (backend unit) is equal to 1 HARD. Same with swap.

**Comment by sunnya97** [comment]
I see

Okay, need to figure out how to deal with that

**Comment by sunnya97** [comment]
I think for now, I think let's just add `HARD` as a denom_unit.  If in the future, we need to change that, we can

**Comment by sunnya97** [comment]
Merging into branch in repo so can edit

**Pull request merged**
