### PR TITLE
Add Allnodes Seed Nodes for multiple blockchains

### PR DESCRIPTION
**Pull request by 3eph1r0th**

### CODE REVIEW

**Review by dylanschultzie — APPROVED** [review]

**Comment by JeremyParish69** [comment]
@3eph1r0th  Please see conflicts

**Comment by JeremyParish69** [comment]
> @JeremyParish69 Please let me know if I resolved conflicts correctly?

Comparing at Files Changed, it looks like you're adding WhisperNodes seeds as well, was that intentional?

**Comment by 3eph1r0th** [comment]
@JeremyParish69 No. I was willing to add only Allnodes seed nodes, but due to unknown reason it got conflicts.

**Comment by 3eph1r0th** [comment]
I will close this pull request and create new ones. It will be easier than to solve these issues.

**Pull request closed without merging**
