### PR TITLE
Add Cosmos SDK and Tendermint Versions

### LINKED ISSUE #40: Include Tendermint and SDK version
`tendermint_version`
`sdk_version`

### PR DESCRIPTION
**Pull request by JeremyParish69**
-Added Cosmos SDK and Tendermint Versions to chain.schema and README
-Added versions to Osmosis' chain.json

Resolves #40 

Notes:
-Includes Major and Minor version number, but not patch nor build.
-There is no 'v' preceding the version number. (e.g., `0.45`, not `v0.45`
-There is no 'x' suffix denoting that patch version doesn't matter. (e.g., `0.45`, not `0.45.x`
-Set both of these versions to 'optional'.

### CODE REVIEW

**Comment by sunnya97** [comment]
Should this be moved into the "codebase" subobject?

**Comment by sunnya97** [comment]
If these are both set to required, then we need to add all of the data to all chain.jsons rn, otherwise they would be invalid

Also, how do we want to deal with non Cosmos SDK based chains?  Like something like nomic for example?

I would suggest keeping as optional for now?

**Comment by JeremyParish69** [comment]
@sunnya97 good feedback.

As for going under codebase, I'm inclined to suggest 'no', at least for now. Although quite related, the codebase section brings with it a new set of required fields (i.e., recommended version, compatible version, and git repo), and some chains prefer not to provide those, or just never bothered to, and so could be more difficult for others to track down. Meanwhile, having only the Cosmos SDK version can still be useful.

As for required vs optional, you've offered some good points, and I agree with you, so I'll change this to optional.

**Comment by sunnya97** [comment]
@jackzampolin thoughts on this?

**Comment by ValarDragon** [comment]
These should be in the codebase section

**Comment by JeremyParish69** [comment]
If we were to put this in the codebase section, could we at least remove the requirement for recommended version, compatible version, and git repo? With that requirement removed, we could much more easily add this Cosmos SDK and Tendermint data for existing chains, which can be useful even without the rest of the codebase data.

**Comment by ValarDragon** [comment]
Who needs to consume the cosmos SDK version and tendermint version, but does not need to build the source code?
 
As time progresses, I think we should push towards codebase required, and these being optional versions in codebase. We just added automation in #431 that will let us get one batch codebase sync PR that chain developers can maintain

**Comment by JeremyParish69** [comment]
> Who needs to consume the cosmos SDK version and tendermint version, but does not need to build the source code?
> 
> As time progresses, I think we should push towards codebase required, and these being optional versions in codebase. We just added automation in #431 that will let us get one batch codebase sync PR that chain developers can maintain

My primary motivation for allowing a place for Cosmos SDK version is to be able to assume some of the 'features' fed into Keplr Suggest Chain so we don't need to manually provide duplicate chain data for each dapp using Keplr. (see #404 )

Could we perhaps try to get the data from that automation first before making it required? The requirements that came with the codebase object is the sole reason I first suggested not putting it there. I fear that by including so many requirements, some chains (such as those who wish to keep their codebase private) will never complete the registration and some apps that want to switch to using the Registry as their data source would be forced to delist some assets.

**Comment by ValarDragon** [comment]
Agreed on not making it required right now!

**Comment by JeremyParish69** [comment]
just want to make sure to not include the v- prefix for these version numbers? I do see the 'v' being used for 'recommended version' and such...

**Comment by pyramation** [comment]
this is cool! for client codgen, this will be nice when we need to build clients during the 0.46 upgrade, and need to keep track of which chains are on the new vs old cosmos sdk.

**Review by ValarDragon — APPROVED** [review]
LGTM, we need to make a corresponding PR on osmosis, since otherwise this will soon get overridden haha

**Pull request merged**
