### PR TITLE
Add THORNode chain info

### PR DESCRIPTION
**Pull request by marius-avram**
THORChain is a decentralised liquidity network built with CosmosSDK.

https://gitlab.com/thorchain/thornode

### CODE REVIEW

**Comment by sunnya97** [comment]
Thanks for this PR!  Much appreciated!

Regarding the RPC endpoints, the field was meant more for the Tendermint rpc endpoints (which are used for broadcasting txs, etc).

It seems these endpoints are more for the nodes of chains connected to i.e. the endpoints of the BTC, ETH, LTC, etc nodes?  

Agree it is useful to have these somewhere, but should probably be a new field.  (You can create a custom field in the json, that's not part of the original schema).

**Comment by marius-avram** [comment]
Updated as per your request. Indeed those endpoints were not valid tendermint rpc endpoints.
I also created the "sidechains_rpc" key where I added the values for BTC, ETH, LTC and so on. 

Hope it has all the required information now.

**Comment by sunnya97** [comment]
Thanks!

**Comment by sunnya97** [comment]
@marius-avram wait why is the chain name thornode instead of thorchain?

**Pull request merged**
