### PR TITLE
update gaiad version to v9.1.0

### PR DESCRIPTION
**Pull request by doggystylez**
pls note: 
* fixed v9 upgrade name
* no upgrade name for v9.1.0 because no `SoftwareUpgradeProposal`

### CODE REVIEW

**Comment by doggystylez** [comment]
oops looks like the bot doesn't like
`"name": null,`
can do
 `"name": "none",` or similar?

**Comment by JeremyParish69** [comment]
> oops looks like the bot doesn't like `"name": null,` can do `"name": "none",` or similar?

null is not a string. But I'd prefer just 'v9.1' over 'none'; makes way more sense, IMO, even if it's not official.

**Comment by doggystylez** [comment]
I think in that case the full tag `v9.1.0` probably would make the most sense. however I also think there maybe should be another field in the schema to indicate whether a consensus breaking upgrade has an upgrade proposal, because if not it must be handled differently than a scheduled upgrade/

**Comment by JeremyParish69** [comment]
> I think in that case the full tag `v9.1.0` probably would make the most sense. however I also think there maybe should be another field in the schema to indicate whether a consensus breaking upgrade has an upgrade proposal, because if not it must be handled differently than a scheduled upgrade/

Wait, so this was an unscheduled consensus-breaking upgrade? I assumed that would never happen, except for maybe emergency patches...
Still I think this having a name makes sense--proposal or not.

**Pull request merged**
