### PR TITLE
Update GEM Icon 

### PR DESCRIPTION
**Pull request by Studio-Mojo**
Update gem.png with corrected sized file.

Thank you!

### CODE REVIEW

**Comment by JeremyParish69** [comment]
The gem image was already updated. This PR tries to add an image to the root directory and we won't allow spaces in the name of the image file. I think this PR can just be closed.

**Comment by Studio-Mojo** [comment]
> The gem image was already updated. This PR tries to add an image to the root directory and we won't allow spaces in the name of the image file. I think this PR can just be closed.

So is the check mark showing which is the current gem.png file that is currently updated?  

85c5fd7   

As the older icon was slightly larger and when it when got cropped to a circle, it cut of part of the logo.  

So just wanted to make sure I had the right file updated.  And Yes, if this is the case then we can close it out.

**Comment by JeremyParish69** [comment]
I see what you're saying. The[ current gem.png](https://github.com/cosmos/chain-registry/blob/master/terra2/images/gem.png) file would lose some detail when cropped to a circle.
You may update the image, but your PR is quite messy right now--I'd suggest starting with a fresh, synchronized branch, and only update the one file with the new one (keep the same file name)

**Comment by Studio-Mojo** [comment]
I also thought the last gem.png I uploaded was smaller than the current one you showed me.  

If that is the case, that is the correct file to be used.

**Comment by Studio-Mojo** [comment]
But if the last file does still get cut, happy to close this out all together and will start fresh with a new PR.

**Comment by JeremyParish69** [comment]
> Is a synchronized branch different than just closing out this PR and starting a new one?
> 
> This is the first time doing this kind of stuff and leaning in real time.

Not necessarily. Your fork's master branch is now behind the Cosmos' branch. You'll want to go to your fork, select the master branch, and synchronize it with the original Cosmos repo. Then you can make a new branch off of master and replace the existing gem.png with the new file, then submit a new PR with that branch.

**Review by Studio-Mojo — COMMENTED** [review]
I confirmed this was the correct file, as I did the same upgrade for ASTRO

https://github.com/astroport-fi/astroport-token-lists/pull/481/commits/451b4d551d4a1573d3f214f7d28d47d3209ad256

I forked ASTRO first to do the update, but getting back to my fork, and master branch to sync is something I have never done.

**Comment by Studio-Mojo** [comment]
@JeremyParish69  I want to say I up it all synced now.

**Comment by Studio-Mojo** [comment]
Screenshot 2024-06-03 at 2 21 55 PM

**Comment by Studio-Mojo** [comment]
Screenshot 2024-06-03 at 2 22 49 PM

I do see the correct file loaded here.  Just don't know how to now get it swithced out with a PR when my master file is still behind the Cosmos chain-registry?

**Comment by JeremyParish69** [comment]
Feel free to reopen or create a new PR if you have the correct fix

**Pull request closed without merging**
