### PR TITLE
Update chain.json to v2.0.2-rc1 release

### PR DESCRIPTION
**Pull request by RaulBernal**

### CODE REVIEW

**Comment by JeremyParish69** [comment]
Can we update the versions array as well, please?

**Comment by JeremyParish69** [comment]
I've assumed that "v2.0.1-rc6" -> "v2.0.2-rc1" is non consensus-breaking.

**Comment by RaulBernal** [comment]
> I've assumed that "v2.0.1-rc6" -> "v2.0.2-rc1" is non consensus-breaking.

Yes is not consensus-breaking.
I'm going to update the versions array.
All the releases have not binary, is it a problem?

**Comment by JeremyParish69** [comment]
>  I'm going to update the versions array. All the releases have not binary, is it a problem?

having binaries for the latest patch of each version object is a nice-to-have. If it's missing here, anyone needing that would just have to dig elsewhere for it.

**Comment by RaulBernal** [comment]
> > I'm going to update the versions array. All the releases have not binary, is it a problem?
> 
> having binaries for the latest patch of each version object is a nice-to-have. If it's missing here, anyone needing that would just have to dig elsewhere for it.

Please hold until Monday, I will update it again with the last barberry upgrade and binary's history as su said

**Comment by JeremyParish69** [comment]
Should this be closed out for https://github.com/cosmos/chain-registry/pull/2417?

**Comment by RaulBernal** [comment]
> Should this be closed out for #2417?

No, it's different, this is DEVNET and 2417 is for MAINNET
Thanks 🙏

**Comment by JeremyParish69** [comment]
> > Should this be closed out for #2417?
> 
> No, it's different, this is DEVNET and 2417 is for MAINNET Thanks 🙏

Ah, yes, you're right. Thanks for clarifying. Will this need any additional update? or is it good to merge now?

**Comment by RaulBernal** [comment]
> > > Should this be closed out for #2417?
> > 
> > 
> > No, it's different, this is DEVNET and 2417 is for MAINNET Thanks 🙏
> 
> Ah, yes, you're right. Thanks for clarifying. Will this need any additional update? or is it good to merge now?

Yes, you can merge it; I also have updated the names setting the right Plan Names

**Pull request merged**
