### PR TITLE
Update firmachain peer by ramuchi

### PR DESCRIPTION
**Pull request by ramuchi**

### CODE REVIEW

**Comment by JeremyParish69** [comment]
Please use a descriptive, non-generic PR title.

**Comment by ramuchi** [comment]
ok

**Comment by JeremyParish69** [comment]
> ok

This is also a poor title. There is no peer.json. It doesn't communicate anything. You could maybe use: 'Update firmachain peer by ramuchi'

**Comment by ramuchi** [comment]
Ok👌

**Pull request merged**
