### PR TITLE
Remove stale endpoints

### PR DESCRIPTION
**Pull request by dylanschultzie**
Removes the following:

```
[-] gitopia rpc http://gitopia.rpc.tarabukin.work:60557
[-] terra rpc https://rpc.terrarebels.net
[-] stride rpc https://rpc.stride.silentvalidator.com
[-] source rpc rpc.source.validatus.com
[-] terra rest https://lcd.terrarebels.net
[-] nois rpc https://rpc-nois.mib.tech
[-] sifchain rpc https://rpc-sifchain-ia.cosmosia.notional.ventures
[-] chain4energy rpc https://rpc-c4e.d-stake.xyz
[-] cosmoshub rpc https://rpc-cosmoshub.blockapsis.com
[-] cosmoshub rpc https://cosmos-rpc.enigma-validator.com
[-] composable rpc https://rpc-centauri.cosmos-spaces.cloud
[-] realio rpc https://realio.rpc.bccnodes.com
[-] gitopia rpc http://gitopia.rpc.nodersteam.com:20657
[-] haqq rpc http://haqq.rpc.nodersteam.com:19657
[-] stride rest https://stride.api.m.stavr.tech
[-] stride rest https://api.stride.silentvalidator.com
[-] sifchain rest https://api-sifchain-ia.cosmosia.notional.ventures
[-] chain4energy rest https://api-m.c4e.hexnodes.co
[-] cosmoshub rest https://cosmoshub-mainnet.api.l0vd.com
[-] gitopia rpc https://rpc-gitopia.nodeist.net
[-] composable rpc https://rpc.composable.validatus.com
[-] stargaze rpc https://stargaze.c29r3.xyz:443/rpc
[-] mises rpc https://w2.mises.site:443
[-] chain4energy rpc https://c4e.rpc.bccnodes.com
[-] nolus rest https://nolus-lcd.sphincs.plus
[-] haqq rest http://haqq.api.nodersteam.com:19017
[-] chain4energy rpc https://c4e-rpc.validatrium.club
[-] composable rest https://api.composable.validatus.com
[-] chain4energy rpc https://rpc-c4e.stakerun.com:443
[-] cosmoshub rest https://cosmos-lcd.enigma-validator.com
[-] neutron rpc https://rpc-neutron.in3s.com:443
[-] composable rest https://api-centauri.cosmos-spaces.cloud
[-] stargaze rest https://stargaze.c29r3.xyz:443/api
[-] neutron rest https://rest-lb.neutron.org
[-] nolus rest https://nolus-lcd.enigma-validator.com
[-] sommelier rpc https://rpc.sommelier.validatus.com
[-] nolus rpc https://nolus-rpc.sphincs.plus
[-] chain4energy rpc https://rpc-m.c4e.hexnodes.co
[-] chain4energy rest https://c4e-api.validatrium.club
[-] chain4energy rest https://lcd-c4e.stakerun.com:443
[-] sommelier rest https://sommelier-api.w3coins.io
[-] humans rpc https://rpc.humans.stakepool.dev.br
[-] chain4energy rpc https://c4e.doubletop.tech
[-] nolus rpc https://nolus-rpc.enigma-validator.com
[-] chain4energy rest https://c4e.api.skynodejs.net
[-] lumenx rpc https://lumenx-rpc.kynraze.com
[-] chain4energy rpc https://c4e.rpc.skynodejs.net
[-] sommelier rest https://api.sommelier.validatus.com
[-] lumenx rest https://api-lumenx.nodine.id
[-] lumenx rest https://lcd.lumenx.hexnodes.co
[-] nomic rest https://rest.nomic.bronbro.io:443
[-] neutron rpc https://rpc-lb.neutron.org
[-] tenet rpc https://tenet-mainnet-rpc.autostake.com:443
[-] bostrom rpc https://rpc.cyber.posthuman.digital
[-] osmosis rest https://api-osmosis.mms.team
[-] humans rpc http://humans.rpc.nodersteam.com:22657
[-] humans rpc https://rpc.humans-mainnet.stake-take.com
[-] bostrom rpc https://rpc-cyber-ia.cosmosia.notional.ventures
[-] humans rpc https://rpc-humans.nodeist.net
[-] rizon rpc https://rpcapi.rizon.world
[-] tenet rest https://tenet-mainnet-lcd.autostake.com:443
[-] rizon rpc https://rizon-rpc.ibs.team
[-] humans rest http://humans.api.nodersteam.com:22017
[-] ethos rpc https://ethos-rpc.provable.dev:443
[-] osmosis rest https://osmosis-mainnet.api.l0vd.com:443
[-] rizon rest https://restapi.rizon.world
[-] humans rest https://api-humans.nodeist.net
[-] ethos rest https://ethos.provable.dev/rest
[-] rizon rest https://rizon-api.ibs.team
[-] bostrom rest https://lcd.cyber.posthuman.digital
[-] humans rest https://rest.humans.stakepool.dev.br
[-] provenance rpc https://rpc-provenance-ia.cosmosia.notional.ventures
[-] provenance rest https://api-provenance-ia.cosmosia.notional.ventures
[-] osmosis rpc https://rpc-osmosis.mms.team
[-] bostrom rest https://api-cyber-ia.cosmosia.notional.ventures
[-] humans rest https://api.humans-mainnet.stake-take.com
[-] mythos rpc https://mythos-rpc.provable.dev:443
[-] fetchhub rpc https://fetch-rpc.teasel.org
[-] uptick rpc http://uptick.rpc.nodersteam.com:21657
[-] cifer rpc https://rpc.mainnet.cifer.ai
[-] mythos rest https://mythos.provable.dev/rest
[-] cifer rest https://mainnet.cifer.ai
[-] uptick rest http://uptick.api.nodersteam.com:21017
[-] kujira rest https://kujira-lcd.wildsage.io
[-] quicksilver rpc http://quicksilver.statesync.nodersteam.com:16657
[-] 8ball rest https://api-8ball.nodine.id
[-] injective rest https://injective-api.w3coins.io
[-] vidulum rest https://api-vdl.nodine.id
[-] bluzelle rpc https://bluzelle-rpc.genznodes.dev
[-] bluzelle rest https://bluzelle-api.genznodes.dev
[-] quicksilver rest http://quicksilver.api.nodersteam.com:16017
[-] oraichain rpc https://rpc-orai.nodine.id
[-] arkh rpc https://asc-dataseed.arkhadian.com
[-] fetchhub rest https://fetch-rest.teasel.org
[-] irisnet rest https://iris-mainnet.api.l0vd.com:443
[-] passage rest https://api-passage-ia.cosmosia.notional.ventures
[-] juno rpc https://rpc-juno.goldenratiostaking.net
[-] gitopia rpc https://rpc.gitopia.sbgid.com
[-] starname rpc https://rpc.starname.cosmos.iov.one
[-] nois rest https://api.nois.nodestake.top
[-] gitopia rpc https://gitopia-rpc.enigma-validator.com
[-] gitopia rest https://api.gitopia.sbgid.com
[-] cosmoshub rpc https://cosmos-rpc.stakeandrelax.net
[-] gitopia rest http://gitopia.api.nodersteam.com:20017
[-] konstellation rpc https://konstellation-rpc.polkachu.com
[-] cosmoshub rpc https://cosmos-rpc.icycro.org
[-] realio rpc https://rpc.realio.nodestake.top
[-] gitopia rest https://api-gitopia.nodeist.net
[-] nois rpc https://rpc.nois.nodestake.top
[-] gitopia rest https://gitopia-lcd.enigma-validator.com
[-] decentr rpc https://rpc-dcntr.nodine.id
[-] decentr rpc https://rpc-decentr.mms.team
[-] conscious rest https://api.consciousdao.com
[-] cosmoshub rest https://lcd-cosmoshub.blockapsis.com
[-] konstellation rest https://konstellation-api.polkachu.com
[-] jackal rpc http://jackal.rpc.nodersteam.com:31657
[-] rebus rest https://rebus-api.kleomedes.network
[-] cosmoshub rest https://cosmos-api.stakeandrelax.net
[-] jackal rest http://jackal.api.nodersteam.com:2917
[-] nois rest https://lcd-nois.mib.tech
[-] terra2 rpc https://terra-mainnet-rpc.autostake.com:443
[-] rebus rpc https://rebus.rpc.manticore.team:443
[-] logos rpc https://logos-rpc.provable.dev:443
[-] rebus rpc http://rebus.statesync.nodersteam.com:18657
[-] terra2 rest https://terra-mainnet-lcd.autostake.com:443
[-] realio rest https://realio.lcd.bccnodes.com
[-] terpnetwork rpc https://rpc.terp.nodestake.top:443
[-] assetmantle rpc https://rpc-assetmantle.blockpower.capital
[-] rebus rpc https://rebus-rpc.kleomedes.network
[-] rebus rest http://rebus.api.nodersteam.com:18017
[-] rebus rest https://rebus.api.manticore.team:443
[-] stratos rest https://api.stratos.nodestake.top
[-] injective rpc https://injective-rpc.quickapi.com:443
[-] stratos rpc https://rpc.stratos.nodestake.top
[-] aura rest https://api.aura.nodestake.top
[-] injective rpc https://rpc.injective.posthuman.digital:443
[-] arkh rpc https://rpc.arkh.nodestake.top
[-] juno rest https://juno-api.reece.sh
[-] juno rest https://rest-juno.goldenratiostaking.net
[-] aura rpc https://rpc.aura.nodestake.top
[-] aura rest https://aura-api.sergo.dev
[-] teritori rpc https://rpc.teritori.nodestake.top
[-] aura rpc https://aura-rpc.sergo.dev
[-] injective rpc https://injective-rpc.w3coins.io
[-] passage rpc https://rpc-passage-ia.cosmosia.notional.ventures
[-] injective rest https://injective-lcd.quickapi.com:443
[-] injective rest https://rest.injective.posthuman.digital:443
[-] odin rpc http://34.79.179.216:26657
[-] starname rpc https://rpc.starname.cosmos.iov.one
[-] logos rest https://logos.provable.dev/rest
[-] terpnetwork rest https://rpc.terp.nodestake.top:443
[-] realio rest https://api.realio.nodestake.top
[-] arkh rest https://asc-blockchain-api.arkhadian.com
[-] teritori rpc https://teritori.rpc.silknodes.io
[-] odin rest http://34.79.179.216:1317
[-] starname rest https://api.starname.cosmos.iov.one
[-] irisnet rpc https://iris-mainnet.rpc.l0vd.com:443
[-] arkh rest https://api.arkh.nodestake.top
[-] bandchain rpc https://rpc-bandchain-ia.cosmosia.notional.ventures
[-] bandchain rest https://api-bandchain-ia.cosmosia.notional.ventures
[-] teritori rest https://api.teritori.nodestake.top
[-] starname rest https://api.starname.cosmos.iov.one
[-] teritori rest https://teritori.api.silknodes.io
```

### CODE REVIEW

**Comment by JeremyParish69** [comment]
I'm leaning to trusting this. What exactly was the process for determining stale endpoint?

**Comment by dylanschultzie** [comment]
@JeremyParish69 I ran Reece's old tool under ~/_scripts.

I then manually checked 6 of them at random, and all "appropriately" didn't work. 

Many of them are the same operators that expired their nodes, like NodeStake and Notional

**Review by JeremyParish69 — APPROVED** [review]

**Comment by keylogic1** [comment]
Hi, 

We were impacted by this PR as it removed our load-balancer RPCs from the list of assets. It looks like the python script that queries the status got blocked by Cloudflare, even though the RPCs are responsive. 

Could you please add the following ones to a whitelist or manual check? We would appreciate it. Thanks

https://rpc-lb.neutron.org

https://rest-lb.neutron.org

The following is the PR where we had the load-balancer listed.

https://github.com/cosmos/chain-registry/commit/481f10034debebce136648b05085ce11e1314977

**Comment by JeremyParish69** [comment]
I was concerned we would be removing so working nodes in the process.
This removed 163 endpoints. Manually checking them all would take a lot of time. Not sure manually checking all of them is realistic.
I wonder what is the best way to handle this? Should nodes that block this (non-abusive) script be removed anyway? Or should we not trust a script because it will raise "false" positives.
IMO a script being run once just to check status should not be blocked.
IMO it's probably worth removing hundreds of stale nodes at the cost of removing a dozen or so working nodes.

**Pull request merged**
