### PR TITLE
Update Osmosis to v14

### PR DESCRIPTION
**Pull request by dylanschultzie**
proposal: https://www.mintscan.io/osmosis/proposals/401
block: 7937500
estimated time: `2023-01-23 07:52:24`

### CODE REVIEW

**Comment by JeremyParish69** [comment]
Nice! Note that for Osmosis automatic update PR come from here: https://github.com/osmosis-labs/osmosis/blob/main/chain.schema.json

**Comment by dylanschultzie** [comment]
@JeremyParish69 oh snap, I didn't realize that. I should close this then?

**Comment by JeremyParish69** [comment]
> @JeremyParish69 oh snap, I didn't realize that. I should close this then?

Probably, although the Osmosis' one might not be updated as quickly if you close this. At least this provides good guidance on the required update info for that file.

**Comment by doggystylez** [comment]
fyi https://github.com/osmosis-labs/osmosis/pull/4072

**Comment by JeremyParish69** [comment]
Thanks. Was updated by automated script.

**Pull request closed without merging**
