### PR TITLE
Feat/migaloo chain

### PR DESCRIPTION
**Pull request by 0xFable**
Adds 3 new assets most importantly ampWHALE and boneWHALE which are now on a few chains.

### CODE REVIEW

**Comment by JeremyParish69** [comment]
Can we not have this try to add submodules? I think it's messing with the structure...

**Comment by 0xFable** [comment]
Do you know how to resolve ser? I think maybe the branch was out of date or something ?

**Comment by JeremyParish69** [comment]
I see a number of issues in the code anyway. I think I can help out by recreating a new PR that just adds the 3 tokens ampwhale, bonewhale, and fable.

I'd like to request from you a scalable SVG of bwhale and fable. We don't accept .jpeg

**Comment by 0xFable** [comment]
@JeremyParish69 would a PNG or SVG be okay ? Got an SVG of ampWHALE and updated to a PNG of bWHALE and fable. SVG is doable but will take a bit longer. 
Happy to help in anyway for this if you are trying to recreate a PR.

**Comment by JeremyParish69** [comment]
I've drafted a PR for the new assets: https://github.com/cosmos/chain-registry/pull/1670
Would you be able to provide long descriptions for each of them?

**Pull request closed without merging**
