### PR TITLE
update comdex main net version

### PR DESCRIPTION
**Pull request by dheerajkd30**

### CODE REVIEW

**Comment by dheerajkd30** [comment]
> Thanks for this. Although I'm confused about whether it went from v9 to v10, and then somehow back down to v9 as if v10 had never happened, I'd like to ask the we retain v9.0 in the versions array--is that possible?

We never upgraded to v10.*, I saw the the PR where it was update to v10 from v9, @reversesigh might have did it by mistake.

**Comment by JeremyParish69** [comment]
Ah, OK thanks for explaining that. Could we please still keep v9.0 in the versions array so it starts to build a history or versions rather than just updating to the latest each time?

**Comment by dylanschultzie** [comment]
Screenshot 2023-06-15 at 11 28 36 AM
I don't believe this is correct, what was trying to be achieved with this PR @dheerajkd30?

**Comment by dylanschultzie** [comment]
closing this due to it being stale

**Pull request closed without merging**
