### PR TITLE
Delete testnets/permtestnet directory 

### PR DESCRIPTION
**Pull request by ahmad-blocksdev**
Due to some organizations issue, have to delete this testnet. kindly remove the directory completely, if possible.

### CODE REVIEW

**Comment by JeremyParish69** [comment]
Can we instead change status to killed, please?

**Comment by ahmad-blocksdev** [comment]
What's the difference between Kill and remove the directory? would you mind to explain?

**Comment by JeremyParish69** [comment]
changing to 'killed' just retains the history so we aren't left wondering what a certain chain or token was and being unable to find any trace of it in the registry. We are already seeing have cases of tokens from killed chains floating around on other chains, and retaining the data helps identify what they are.

**Comment by ahmad-blocksdev** [comment]
> changing to 'killed' just retains the history so we aren't left wondering what a certain chain or token was and being unable to find any trace of it in the registry. We are already seeing have cases of tokens from killed chains floating around on other chains, and retaining the data helps identify what they are.

Yes. you can change the status to killed.

**Pull request closed without merging**
