### PR TITLE
Add IBC data for Secret Network

### PR DESCRIPTION
**Pull request by assafmo**

### CODE REVIEW

**Comment by pyramation** [comment]
this is awesome! ⚛️🙌🏻

**Review by JeremyParish69 — CHANGES_REQUESTED** [review]
The checks fail because the order in which chains are listed in the name of the file is not always alphabetical. Please change most of the file names to instead have the other chain name first (e.g., use 'akash-secretnetwork.json' instead of 'secretnetwork-akash.json', because 'a' comes before 's') all the way to scrt-juno, but the remainder (scrt-sentinel to scrt-terra2 are correct)

**Comment by assafmo** [comment]
> The checks fail because the order in which chains are listed in the name of the file is not always alphabetical. Please change most of the file names to instead have the other chain name first (e.g., use 'akash-secretnetwork.json' instead of 'secretnetwork-akash.json', because 'a' comes before 's') all the way to scrt-juno, but the remainder (scrt-sentinel to scrt-terra2 are correct)

Thanks! Didn't know it was a requirement.

**Comment by assafmo** [comment]
Cool

**Review by JeremyParish69 — APPROVED** [review]

**Pull request merged**
