### PR TITLE
Add meme chain.svg

### PR DESCRIPTION
**Pull request by iloveanyujin**

### CODE REVIEW

**Comment by JeremyParish69** [comment]
Can I ask your opinion on this PR, which contains a true vector image?
https://github.com/cosmos/chain-registry/pull/1672

**Comment by ankurdotb** [comment]
Would close this PR and consider it superseded by #1672

**Comment by JeremyParish69** [comment]
@iloveanyujin any comment?

**Comment by iloveanyujin** [comment]
I decided to close this request. Thank you.

**Pull request closed without merging**
