### PR TITLE
Kill old Odin and create new Odin for fork

### PR DESCRIPTION
**Pull request by reversesigh**

### CODE REVIEW

**Comment by reversesigh** [comment]
Waiting on genesis to be made public and a few other details

**Comment by JeremyParish69** [comment]
Made a few changes that addressed my comment. Is this good to merge now? @reversesigh

**Comment by reversesigh** [comment]
I was about to say yes but then realized I should double check genesis - and they haven't listed the new genesis on their repo yet. Let me find a safe alternative until then.

**Comment by JeremyParish69** [comment]
Since I saw an update but am not sure if you're finished (It still says WIP in the title). Could I ask you to merge when you think it's ready?

**Pull request merged**
