### PR TITLE
bluechip-1 to bluechip-2

### PR DESCRIPTION
**Pull request by Bluechip23**
We originally had changed out chain-Id but after doing so, we ran into multiple issues with syncing to other nodes and IBC issues. We upgraded our chain at created a new one. Everything else about the chain is the same.

### CODE REVIEW

**Comment by Bluechip23** [comment]
@JeremyParish69 To be clear, we have launched a new chain due to errors we were having with IBC and peer to peer communication issues after chainid change. I pushed new data to this chain becuase I am not 100% sure how the registry works. If I need to delete this chain from registry completely and create new push I am happy to do this. The new chain is the exact same outside the changes I have made to this push. Sorry for any inconvenience

**Comment by JeremyParish69** [comment]
Normally we would have the old version (bluechip-1) be archived and the new version would take its place in this directory, but since there doesn't seem to be much integration and no ibc connections registered, we may be able to update a few values in place as you have.
If this is a new chain, does it need a genesis with addresses and balances?

**Comment by Bluechip23** [comment]
I am not entirely sure what you are asking. This is a new chain that has a new genesis file of addresses and balances. 
The link to the genesis is the same link, and I updated the validators address in the push to make sure it was no longer the old one.

**Comment by JeremyParish69** [comment]
> I am not entirely sure what you are asking. This is a new chain that has a new genesis file of addresses and balances. The link to the genesis is the same link, and I updated the validators address in the push to make sure it was no longer the old one.

I was thinking that the link to the genesis file must be different and should have at least hundreds of balances in it, but I see it was updated 2 weeks ago, and I guess there just hasn't been any usage of the old chain at all because I see only 2 balance in now.

**Pull request merged**
