### PR TITLE
Update dHealth IBC data due to expired legacy one

### PR DESCRIPTION
**Pull request by nsonanh**

### CODE REVIEW

**Comment by JeremyParish69** [comment]
Is there any proof that the previous connection wasn't used and that no tokens are abandoned on either chain?
Generally, registered IBC connections cannot be replaced in the registry, and expired clients should be revived via governance rather than new ones be created.

**Comment by nsonanh** [comment]
@JeremyParish69 If my client is expired, how can I renew it ?

**Comment by JeremyParish69** [comment]
I'm not an expert in this, but there a proposal type for renewing the light client, and this can preserve the existing ibc channel.

**Comment by nsonanh** [comment]
> Is there any proof that the previous connection wasn't used and that no tokens are abandoned on either chain?
Generally, registered IBC connections cannot be replaced in the registry, and expired clients should be revived via governance rather than new ones be created.

It wasn't used except by me. Is it possible that we update this once ?

**Comment by JeremyParish69** [comment]
I figure you're probably right, since it wasn't listed on Osmosis yet. I'll ask if there's any app that can show that there were only a few small transfers?

**Comment by nsonanh** [comment]
This is from my relayer cli, If it can help:
image

**Comment by nsonanh** [comment]
image

**Comment by JeremyParish69** [comment]
I mean like a block explorer that shows all transfers

**Comment by nsonanh** [comment]
Oh ok. These are:
- [Big Dipper](https://explorer.dhealth.com/dhealth)
- [NodeStake](https://explorer.nodestake.org/dhealth)
- [EzStaking](https://ezstaking.app/dhealth)

**Comment by nsonanh** [comment]
Ok, these are the total (un-relayed) transfer transactions in descending order:
1. https://explorer.dhealth.com/dhealth/transactions/D1C6CAF8D918BD8D937452765B6DBAA47C3CE826016B947F00E0A8D488C9C302
2. https://explorer.dhealth.com/dhealth/transactions/34FE2C833226D38E93C114BE30C7345E37294C0188A8ED166985398BC19512FC
3. https://explorer.dhealth.com/dhealth/transactions/17E0128E0A1DEEED2A27504E97D48F603D4DCEB8BBE95F1E76AF80937BFF6351
4. https://explorer.dhealth.com/dhealth/transactions/DC8F38C09FDE9584FFF605E4D6053D6776808B43B25848163BE1079309BE3218
5. https://explorer.dhealth.com/dhealth/transactions/AE489B7BC2FCCBC48CB5E158D7D3938614517FD6E26B74BDB49F96E102775458
6. https://explorer.dhealth.com/dhealth/transactions/F64BEBC362A8499C833F9211C1A53983996155B50F47B7239B1E884CD0350CA5
7. https://explorer.dhealth.com/dhealth/transactions/52CE0705775C8D6DE92221E35DFC546D0E118F0CF7F1BC07D2D22CC664363EC0
8. https://explorer.dhealth.com/dhealth/transactions/F26C7F01591197C2E899B44855FA9B0AD2C45971738037328566C53B1A2B1DD7
9. https://explorer.dhealth.com/dhealth/transactions/7827E681AACC4B11429BF86F7B9140A7E4BF91C9C923684231DEDFBDC1E063BC
10. https://explorer.dhealth.com/dhealth/transactions/40C87950DFD0F102ED3EB2FEB777490D6CFB0C7D8BFF584F7A5C38B9B830B1B8
11. https://explorer.dhealth.com/dhealth/transactions/349A39649DD15F65817BE125F13CE9524AF61A8900A43984F6EA8FAC6BF7EAB9 

These 2 accounts created all of these 11 transfer transactions:
1. https://explorer.dhealth.com/dhealth/accounts/dh1flz9s59sted5qmtpx4p0pxkjd4xlc7mjardk7j
2. https://explorer.dhealth.com/dhealth/accounts/dh16v4ttqac7rmckur3mvxp6hf0hw5swvcuss3jtk

**Pull request merged**
