### PR TITLE
Add TAKUMI to Neutron asset list.json

### PR DESCRIPTION
**Pull request by NEXXGENAI**
Add TAKUMI to Neutron asset list

### CODE REVIEW

**Comment by JeremyParish69** [comment]
Please fix the schema, please use appropriate PR title, please add token logo image in the same PR.

**Comment by NEXXGENAI** [comment]
takumi

**Comment by NEXXGENAI** [comment]
> Please fix the schema, please use appropriate PR title, please add token logo image in the same PR.

I've updated the schema, title and added a token logo.  

- Paul

**Comment by JeremyParish69** [comment]
Please add the token in this PR (not as a comment in the discussions, but into the appropriate directory).
Also please use an appropriate PR title, and not the generic commit text.

**Comment by NEXXGENAI** [comment]
> Please add the token in this PR (not as a comment in the discussions, but into the appropriate directory). Also please use an appropriate PR title, and not the generic commit text.

I changed the PR title, but I am having trouble with getting the logo file to upload.  Are you able to help?  I edited the image size to 250x250 as seen below.

takumi

**Comment by JeremyParish69** [comment]
> I changed the PR title, but I am having trouble with getting the logo file to upload. Are you able to help? I edited the image size to 250x250 as seen below.

In your branch, NEXXGENAI:patch-4, you go to the neutron/images/ directory and upload there.

**Comment by NEXXGENAI** [comment]
> > I changed the PR title, but I am having trouble with getting the logo file to upload. Are you able to help? I edited the image size to 250x250 as seen below.
> 
> In your branch, NEXXGENAI:patch-4, you go to the neutron/images/ directory and upload there.

Done, thank you.  I had clicked on add file instead of upload by mistake for the image file.  Anything else that needs correcting?

Paul

**Comment by JeremyParish69** [comment]
> Done, thank you. I had clicked on add file instead of upload by mistake for the image file. Anything else that needs correcting?

I think it's otherwise fine now, although the image really should have a square aspect ratio. And maybe the name is meant to be "Takumi Asano" (currently name is just "takumi")

**Pull request merged**
