### PR TITLE
API clean up (part 1)

### PR DESCRIPTION
**Pull request by staking-explorer**
https://aura-api.ramuchi.tech/cosmos/base/tendermint/v1beta1/node_info ERROR CHAIN (returns stargaze-1 but must be xstaxy-1)

https://rest-mars.carbonZERO.zone:443/cosmos/base/tendermint/v1beta1/node_info ERROR CHAIN (returns migaloo-1 but must be mars-1)

https://lcd-jackal.whispernode.com:443/cosmos/base/tendermint/v1beta1/node_info ERROR CHAIN (returns osmosis-1 but must be jackal-1)

### CODE REVIEW

**Comment by staking-explorer** [comment]
We apologize for initially assuming that some validators intentionally made such mistakes (we haven't slept for 3 months). It is now obvious to us that such errors are made by accident. It's just that the validators mixed up something in the DNS/IP. And sometimes validators run out of space on the server and such nodes simply freeze on a certain block. We will publish a list of such nodes in the second part.

**Comment by gh0stdotexe** [comment]
> https://aura-api.ramuchi.tech/cosmos/base/tendermint/v1beta1/node_info ERROR CHAIN (returns stargaze-1 but must be xstaxy-1)
> 
> https://rest-mars.carbonZERO.zone:443/cosmos/base/tendermint/v1beta1/node_info ERROR CHAIN (returns migaloo-1 but must be mars-1)
> 
> https://lcd-jackal.whispernode.com:443/cosmos/base/tendermint/v1beta1/node_info ERROR CHAIN (returns osmosis-1 but must be jackal-1)

Fixed - we had a misconfiguration in our Jackal `client.toml` that was pointing to the default `26657` RPC port - my bad!

**Comment by ramuchi** [comment]
I have the same error as gh0stdotexe, corrected thanks!

**Comment by staking-explorer** [comment]
Thank you, guys. Now everything is as it should be. The question is closed.

**Pull request closed without merging**
