### PR TITLE
Add juno testnet gRPC endpoint

### PR DESCRIPTION
**Pull request by de-husk**
Adds the polkachu juno testnet gRPC endpoint to config.

I tested that the gRPC url works, and it also follows the same format as the other Polkachu gRPC urls.

### CODE REVIEW

**Comment by psibi** [comment]
I don't think it works anymore.

**Comment by de-husk** [comment]
gRPC is working for me. Its the first RPC endpoint that is working for me right now: https://rpc.uni.junomint.com

**Comment by psibi** [comment]
@de-husk Maybe I'm missing something here, but the test gRPC endpoint doesn't seem to be working for me:

```
❯ grpcurl juno-testnet-grpc.polkachu.com:12690 list
Failed to dial target host "juno-testnet-grpc.polkachu.com:12690": tls: first record does not look like a TLS handshake
```

**Comment by de-husk** [comment]
> @de-husk Maybe I'm missing something here, but the test gRPC endpoint doesn't seem to be working for me:
> 
> ```
> ❯ grpcurl juno-testnet-grpc.polkachu.com:12690 list
> Failed to dial target host "juno-testnet-grpc.polkachu.com:12690": tls: first record does not look like a TLS handshake
> ```

Have you tried `-plaintext`?

**Comment by psibi** [comment]
Thanks, that is indeed working.

**Pull request merged**
