### PR TITLE
feat: add historical versions key

### PR DESCRIPTION
**Pull request by czarcas7ic**
Closes: #521
Closes: #130  

Adds a `genesis_version` key for users to know what version to start with.

Adds a `historical_versions` key that shows each upgrade and its respective height (note the name and upgrade tag mismatch. This is on purpose due to them being forks)

### CODE REVIEW

**Review by ValarDragon — APPROVED** [review]

**Comment by ValarDragon** [comment]
cc @JeremyParish69 can you update the schema (feel free to edit this branch), and we can get this in?

**Comment by JeremyParish69** [comment]
some questions and suggestions:


1) I'd suggest removing "genesis_version" as its own property, but just putting that version as the first version object within the "historical_versions" array.
2) Does genesis always necessarily start at height 0? If so, height 0 can be the indication of genesis version--otherwise, another property might be required.
3) Could it be useful to have some way to show the next version to help ensure that there are no gaps in version history? E.g., someone could see Osmosis version going from v5 -> 7 -> v9 and wonder if version 6 and 8 were skipped.
4) Could be useful to have a property for the date of version upgrade to help guide readers?
5) What exactly is an 'upgrade tag'? Is this precise universal terminology? I might suggest "id" as an alternative; unless that's too vague.
6) Would it make sense to allow for a URL with each version? We could pair not only the genesis URL with the genesis version, but also a pruned state URL with later versions (would that work?).
7) Want to move "genesis_url" to codebase--just makes sense to me.
8) Want to allow for a "compatible_versions" list with each version. (see drafted schema)

**Comment by czarcas7ic** [comment]
> some questions and suggestions:
> 
> 1. I'd suggest removing "genesis_version" as its own property, but just putting that version as the first version object within the "historical_versions" array.
> 2. Does genesis always necessarily start at height 0? If so, height 0 can be the indication of genesis version--otherwise, another property might be required.
> 3. Could it be useful to have some way to show the next version to help ensure that there are no gaps in version history? E.g., someone could see Osmosis version going from v5 -> 7 -> v9 and wonder if version 6 and 8 were skipped.
> 4. Could be useful to have a property for the date of version upgrade to help guide readers?
> 5. What exactly is an 'upgrade tag'? Is this precise universal terminology? I might suggest "id" as an alternative; unless that's too vague.
> 6. Would it make sense to allow for a URL with each version? We could pair not only the genesis URL with the genesis version, but also a pruned state URL with later versions (would that work?).
> 7. Want to move "genesis_url" to codebase--just makes sense to me.
> 8. Want to allow for a "compatible_versions" list with each version. (see drafted schema).
> 9. Want to allow for a list of names. E.g., Osmosis has also used chemical elements as version identifiers, and not only version numbers.

1. Sounds good
2. Technically its possible to be non zero, but its a fine assumption to make
3. I would just put the same version tags for the missing versions, I am fine with either way
4. I think the version number increments is sufficient and getting all chains to pull dates might be difficult
5. "tag" was used since its the github tag used that the user needs to pull. I think tag is better than ID
6. If there was a URL for each version it would be a URL to either the github tag or to the raw binaries link
7. I have no preference so either is fine to me
8. That might get messy / I just think listing the latest version for that height is all thats needed
9. No preference

**Comment by JeremyParish69** [comment]
the next step would be to update all the existing chain.json schema to use this, and then remove the "binaries" and "genesis_url" objects from the top level (because it'll then already be in the codebase section)

**Comment by czarcas7ic** [comment]
@JeremyParish69 Yeah what you pushed makes total sense to me, well done!

**Comment by sunnya97** [comment]
This looks pretty good to me

**Pull request merged**
