### PR TITLE
Added brand assets

### PR DESCRIPTION
**Pull request by grahamprovenance**

### CODE REVIEW

**Comment by sunnya97** [comment]
Can you put this in a subfolder called `images`

**Comment by iramiller** [comment]
The problem with these is that these versions are not well suited (color wise) to most of the explorer/web interfaces (including osmosis).  

Compare to the hash svg/png here: https://github.com/iramiller/assetlists/tree/provenance-assets/images

**Comment by grahamprovenance** [comment]
I had never seen the HASH logo in the blue color, only black and white. I
can add this version.
<http://provenance.io/>

*Graham Kahr*
Vice President of Marketing, Provenance Blockchain
c: 702.533.8680
650 California St. | Suite 2700 | San Francisco, CA 94108

Provenance.io <http://provenance.io/>  |  Book a meeting
<https://calendly.com/gkahr/30min>  |  Join our Discord
<https://discord.gg/UZaSkC8dMA>  |  Follow us on Twitter
<https://twitter.com/provenancefdn>

**Comment by iramiller** [comment]
(side note: the branch/PR for Osmosis assetlists is pending our finalizing IBC channels/config--when this is complete we can add that denom info and submit a PR to Osmosis)

**Pull request closed without merging**
