### PR TITLE
Update persistence-quicksilver.json

### PR DESCRIPTION
**Pull request by napelvs**
The previous IBC Channel between the chains has expired. Since I was the only operator on the channel, I decided to create another one instead of resurrecting the old one through a governance proposal.

### CODE REVIEW

**Comment by JeremyParish69** [comment]
Are there governance proposals on both sides showing agreement to switching to a new channel? Alternatively, if no tokens are stuck on their non-native chain it should be OK.

**Comment by napelvs** [comment]
The other channel expired. So we've opened another one.

**Comment by JeremyParish69** [comment]
We can't switch to new channels without compromising the integrity to tokens that had already been transferred. If we can neither show that there are no abandoned tokens from the old channel, nor that governance on both chains has approved switching to a new channel, we cannot accept this new channel as 'canon' and therefore will not register it.

**Comment by napelvs** [comment]
So the channel was only used by me and then expired. The only assets on that path are mine and are close to $0 (0.00020 XPRT on the Persistence side, and 0.00030 XPRT on the Quicksilver side).

You can verify the address is mine by looking at the memo of the "IBC Acknowledgement" and/or "IBC Received" TXs.

My Quicksilver Wallet: https://www.mintscan.io/quicksilver/account/quick15rwjpdn2cjunek9g0sqmehwd4ht3nz0fkzx673
My Persistence Wallet: https://www.mintscan.io/persistence/account/persistence1m3hsmmf633nl5dl8sm58dypu4fthppe7ej463y

**Pull request merged**
