### PR TITLE
update assetlist for cw20 schema

### PR DESCRIPTION
**Pull request by IbrarMakaveli**

### CODE REVIEW

**Comment by sunnya97** [comment]
@IbrarMakaveli if we're changing the schema to use `type_asset` instead of `kind`, can you please make sure to update all the existing assetlists.  For example Terra's:  https://github.com/cosmos/chain-registry/blob/master/terra/assetlist.json#L71

**Comment by IbrarMakaveli** [comment]
@sunnya97 Yep, make the change, you can see in the "Files changed"

**Comment by jasbanza** [comment]
@IbrarMakaveli the Neta png is a 404

"logo_URIs": {
          "png": "https://raw.githubusercontent.com/osmosis-labs/assetlists/main/images/neta.png"
        }

**Comment by jasbanza** [comment]
@IbrarMakaveli the `cosmos/chain-registry` URL for Neta's image points to:
https://raw.githubusercontent.com/osmosis-labs/assetlists/main/images/neta.png

but the `osmosis-labs/assetlists` points to the following (which is now a 404):
https://raw.githubusercontent.com/cosmos/chain-registry/master/juno/images/neta.png

**Comment by sunnya97** [comment]
@jasbanza can you make and issue and/or pr to update the cosmos/chain-registry version to use the chain-registry's image.

**Comment by jasbanza** [comment]
@sunnya97 Alrighty, I'll do so. However, I see there there isn't a neta.png in cosmos/chain-registry, so I'll grab it from the osmosis repo. #323 doing PR now

**Pull request merged**
