### PR TITLE
add rebus chain

### PR DESCRIPTION
**Pull request by Galadrin**

### CODE REVIEW

**Comment by nicolam1** [comment]
This is not approved by the Rebuschain team

**Comment by sunnya97** [comment]
@nicolam1 are you with the Rebuschain team?

**Comment by sunnya97** [comment]
Gotcha.  Can you send me a DM on telegram for a separate matter?  (sunnya97)

**Comment by nicolam1** [comment]
@sunnya97 I did

**Comment by troian** [comment]
@nicolam1 any plans to release it?

**Comment by nicolam1** [comment]
@troian we are working on the official set up and we'll create the correct PR this even has wrong information in it. It should be declined

**Comment by Galadrin** [comment]
@nicolam1 will create the correct one

**Pull request closed without merging**
