### PR TITLE
Adding Stateset

### PR DESCRIPTION
**Pull request by domsteil**
Adding Stateset testnet information.

### CODE REVIEW

**Comment by sunnya97** [comment]
lets figure out a place to put testnets.  Also, the chain name here should be something other than `stateset` because I imagine you want to reserve that name for your mainnet?

**Comment by nooomski** [comment]
Why don't we just create a `testnet` folder inside each chain's directory? And inside the testnet folder you can have multiple folders in case you have multiple testnets running.

**Comment by sunnya97** [comment]
Testnets should have a different chain-name than mainnets, and so would prefer to keep the folder -> chain name linkage

**Comment by sunnya97** [comment]
I think maybe creating one testnets folder, and then put a bunch of subfolders in there for each testnet chain?

**Comment by nooomski** [comment]
Yeah, that makes sense. Let's do that.

**Comment by nooomski** [comment]
Closed for #191

**Pull request closed without merging**
