### PR TITLE
Update composable-injective.json

### PR DESCRIPTION
**Pull request by lichdu29**

### CODE REVIEW

**Comment by JeremyParish69** [comment]
Changing IBC connections can be quite problematic. Do we have any proof the the originally used connection has little to no funds transferred (and to be abandoned)?

**Comment by lichdu29** [comment]
Well the composable team ask us to do that, I am also the one wgo create the previous channel and it is expried

**Comment by lichdu29** [comment]
and yes there are no funds on that channel @JeremyParish69 so we decide to create a new channel instead of reviving it by gov

**Comment by JeremyParish69** [comment]
OK I found this: https://www.mintscan.io/injective/relayers/channel-141/not-established/channel-10

**Pull request merged**
