### PR TITLE
Add new coreum IBC channel

### PR DESCRIPTION
**Pull request by jayjay-crypto**

### CODE REVIEW

**Comment by JeremyParish69** [comment]
Did you mean to leave this PR in draft state?

**Comment by jayjay-crypto** [comment]
> Did you mean to leave this PR in draft state?

**Comment by jayjay-crypto** [comment]
Hi Jeremy, I’m just waiting for notional to add the channels they opened to my PR, and for the coreum team to finish their test and give me the green light.
I hope it will be fast

**Comment by JeremyParish69** [comment]
> Hi Jeremy, I’m just waiting for notional to add the channels they opened to my PR, and for the coreum team to finish their test and give me the green light. I hope it will be fast

Ok, no worries, just making sure there wasn't miscommunication. Setting to 'Ready' should suffice or feel free to ping me once ready.

**Comment by hakuno2000** [comment]
@jayjay-crypto can you pls add access permission for this account to allow me push code to your forked repo

**Comment by wanesurf** [comment]
Ok for me

**Comment by wanesurf** [comment]
Please do not merge!

**Comment by wanesurf** [comment]
DYDX Channel have expired and the secret channel is not working

**Pull request merged**
