### PR TITLE
Remove Asset from Bitsong

### PR DESCRIPTION
**Pull request by angelorc**
remove discontinued fantokens

### CODE REVIEW

**Comment by angelorc** [comment]
I agree with you. However, the artist had an agreement with us and wishes for their image and name to be removed. We would also prefer it to be taken off the asset lists, so it doesn't appear among the other tokens. Moreover, in a few days, artists will be able to customize metadata using the URI field available on the fan token itself within the BitSong chain

**Comment by JeremyParish69** [comment]
Perhaps we can decommission it without removing it to give artists freedom to remove their identity. Could we update the name, description, and images to remove their identity, and use placeholder values instead?

**Comment by JeremyParish69** [comment]
@angelorc Please see this PR: https://github.com/cosmos/chain-registry/pull/3760
I think this new property could signal to interfaces to exclude this asset by default.

**Comment by angelorc** [comment]
That's good, but we should remove also the name and the image, the artist no longer wants any reference to him.

**Comment by JeremyParish69** [comment]
> That's good, but we should remove also the name and the image, the artist no longer wants any reference to him.

The images were already removed. But I've made a few more changes, removing more of the references to them, substituting a generic value or [Redacted] where their name was. The only remaining reference now is in the symbol property.

**Comment by angelorc** [comment]
Thank you Jeremy

**Pull request closed without merging**
