### PR TITLE
update ibc path dydxtestnet-osmosistestnet

### PR DESCRIPTION
**Pull request by clemensgg**

### CODE REVIEW

**Comment by JeremyParish69** [comment]
oh, dydxtestnet chain hasn't been registered yet. Could we get that in here as well?

**Comment by clemensgg** [comment]
@JeremyParish69 I think the current private testnet isn't intended to, but we'll add the public dydx testnet as soon it is launched!

**Comment by JeremyParish69** [comment]
> @JeremyParish69 I think the current private testnet isn't intended to, but we'll add the public dydx testnet as soon it is launched!

So this is the private testnet? Just don't want that to get confusing. We'd need to make sure the public testnet doesn't get registered as dydxtestnet, then, or else this connection would be inaccurate. Maybe if the chain isn't going to be registered we should call it something like 'dydxprivatetestnet' ?

**Comment by clemensgg** [comment]
> 

updated suggested changes

**Pull request merged**
