### PR TITLE
Inj scrt ibc

### PR DESCRIPTION
**Pull request by PFC-developer**
update the Injective/Secret IBC channel (one in there was expired)

### CODE REVIEW

**Comment by JeremyParish69** [comment]
Do we have proof that no coins were transferred on the old channel? Alternatively, (and preferred) we can use proof of governance on both chains voting to change the ibc connection. Otherwise users will be left with non-fungible ibc coins by switching channels, and re-enabling the expired channel is preferred.

**Comment by PFC-developer** [comment]
This happened months ago. 
at the time, I think these were checked, and decided that this was ok.
Feel free to contact the SCRT or INJ maintainers to verify

**Comment by JeremyParish69** [comment]
You're right. I could verify that the old channel is abandoned with no activity for ~9 months. Meanwhile, this new one has been around a while and is very active. I take this activity as proof of canon and not going to be disruptive. Thanks for the submission.

**Comment by PFC-developer** [comment]
🙏

**Pull request merged**
