### PR TITLE
Update lambda mainnet info

### PR DESCRIPTION
**Pull request by steveliupai**
1. Update IBC info, replace expired client
2. Add more peers

@JeremyParish69 Hi, lambda info updated ,please review and merge, thank you!

### CODE REVIEW

**Comment by tombeynon** [comment]
@steveliupai can you shed any light on #847? Should the slip44 path be 118 or 60 for Lambda?

**Comment by steveliupai** [comment]
> @steveliupai can you shed any light on #847? Should the slip44 path be 118 or 60 for Lambda?

Just fixed this

**Comment by tombeynon** [comment]
Amazing thank you!

**Comment by steveliupai** [comment]
> Amazing thank you!

Thank you so much for pointing out the wrong coin type!!

**Review by ankurdotb — APPROVED** [review]

**Pull request merged**
