### PR TITLE
NakoTurk Registry C4eTest chain.json

### PR DESCRIPTION
**Pull request by okannako**

### CODE REVIEW

**Comment by JeremyParish69** [comment]
Is this for c4e testnet?

**Comment by okannako** [comment]
> Is this for c4e testnet?

mainnet

**Comment by okannako** [comment]
> Is this for c4e testnet?

https://cosmos.directory/chain4energy/nodes

Hello, will it be added to the list here?

**Comment by JeremyParish69** [comment]
> https://cosmos.directory/chain4energy/nodes
> 
> Hello, will it be added to the list here?

Yes, it is already there.

**Comment by okannako** [comment]
> > https://cosmos.directory/chain4energy/nodes
> > Hello, will it be added to the list here?
> 
> Yes, it is already there.

No, it's not. I still can't see

**Comment by okannako** [comment]
> > https://cosmos.directory/chain4energy/nodes
> > Hello, will it be added to the list here?
> 
> Yes, it is already there.

Hello
I'm still not on this list, when will it be added?

**Comment by JeremyParish69** [comment]
> > > https://cosmos.directory/chain4energy/nodes
> > > Hello, will it be added to the list here?
> > 
> > 
> > Yes, it is already there.
> 
> Hello I'm still not on this list, when will it be added?

cosmos.directry is a third party app, and maintainers of this repo don't maintain it. This should instead be brought up with Eco Stake.
That being said, I do see it there under the APIs, GRPC tab, so I see nothing wrong.
image

**Pull request merged**
